code_dict = {
 'CELTIC': ['Celtic languages', '', ''],
 'NORTH_EU': ['NORTH_EU', '', ''],
 'NORWAY': ['Norwegian', '', ''],
 'ROMANCE': ['Romance languages', '', ''],
 'SAMI': ['Sami', '', ''],
 'SCANDINAVIA': ['Scandinavia', '', ''],
 'ZH': ['Chinese', 'ZH', ''],
 'aa': ['Afar', 'aa', 'aar'],
 'aar': ['Afar', 'aa', 'aar'],
 'aav': ['Austro-Asiatic languages', '', 'aav'],
 'ab': ['Abkhazian', 'ab', 'abk'],
 'abk': ['Abkhazian', 'ab', 'abk'],
 'ace': ['Achinese', ' ', 'ace'],
 'ach': ['Acoli', ' ', 'ach'],
 'ada': ['Adangme', ' ', 'ada'],
 'ady': ['Adyghe', ' ', 'ady'],
 'ae': ['Avestan', 'ae', 'ave'],
 'aed': ['Argentine Sign Language', '', 'aed'],
 'af': ['Afrikaans', 'af', 'afr'],
 'afa': ['Afro-Asiatic languages', ' ', 'afa'],
 'afh': ['Afrihili', ' ', 'afh'],
 'afr': ['Afrikaans', 'af', 'afr'],
 'ain': ['Ainu', ' ', 'ain'],
 'ak': ['Akan', 'ak', 'aka'],
 'aka': ['Akan', 'ak', 'aka'],
 'akk': ['Akkadian', ' ', 'akk'],
 'alb/sqi': ['Albanian', 'sq', 'alb/sqi'],
 'ale': ['Aleut', ' ', 'ale'],
 'alg': ['Algonquian languages', ' ', 'alg'],
 'alt': ['Southern Altai', ' ', 'alt'],
 'alv': ['Atlantic-Congo languages', '', 'alv'],
 'am': ['Amharic', 'am', 'amh'],
 'amh': ['Amharic', 'am', 'amh'],
 'an': ['Aragonese', 'an', 'arg'],
 'ang': ['English, Old (ca.450-1100)', ' ', 'ang'],
 'anp': ['Angika', ' ', 'anp'],
 'apa': ['Apache languages', ' ', 'apa'],
 'ar': ['Arabic', 'ar', 'ara'],
 'ara': ['Arabic', 'ar', 'ara'],
 'arc': ['Official Aramaic (700-300 BCE)', ' ', 'arc'],
 'arg': ['Aragonese', 'an', 'arg'],
 'arm/hye': ['Armenian', 'hy', 'arm/hye'],
 'arn': ['Mapudungun', ' ', 'arn'],
 'arp': ['Arapaho', ' ', 'arp'],
 'art': ['Artificial languages', ' ', 'art'],
 'arw': ['Arawak', ' ', 'arw'],
 'as': ['Assamese', 'as', 'asm'],
 'ase': ['American Sign Language', '', 'ase'],
 'asm': ['Assamese', 'as', 'asm'],
 'ast': ['Leonese', ' ', 'ast'],
 'ath': ['Athapascan languages', ' ', 'ath'],
 'aus': ['Australian languages', ' ', 'aus'],
 'av': ['Avaric', 'av', 'ava'],
 'ava': ['Avaric', 'av', 'ava'],
 'ave': ['Avestan', 'ae', 'ave'],
 'awa': ['Awadhi', ' ', 'awa'],
 'ay': ['Aymara', 'ay', 'aym'],
 'aym': ['Aymara', 'ay', 'aym'],
 'az': ['Azerbaijani', 'az', 'aze'],
 'aze': ['Azerbaijani', 'az', 'aze'],
 'ba': ['Bashkir', 'ba', 'bak'],
 'bad': ['Banda languages', ' ', 'bad'],
 'bai': ['Bamileke languages', ' ', 'bai'],
 'bak': ['Bashkir', 'ba', 'bak'],
 'bal': ['Baluchi', ' ', 'bal'],
 'bam': ['Bambara', 'bm', 'bam'],
 'ban': ['Balinese', ' ', 'ban'],
 'baq/eus': ['Basque', 'eu', 'baq/eus'],
 'bas': ['Basa', ' ', 'bas'],
 'bat': ['Baltic languages', ' ', 'bat'],
 'bcl': ['Central Bikol', '', 'bcl'],
 'be': ['Belarusian', 'be', 'bel'],
 'bej': ['Beja', ' ', 'bej'],
 'bel': ['Belarusian', 'be', 'bel'],
 'bem': ['Bemba', ' ', 'bem'],
 'ben': ['Bengali', 'bn', 'ben'],
 'ber': ['Berber languages', ' ', 'ber'],
 'bg': ['Bulgarian', 'bg', 'bul'],
 'bh': ['Bihari languages', 'bh', 'bih'],
 'bho': ['Bhojpuri', ' ', 'bho'],
 'bi': ['Bislama', 'bi', 'bis'],
 'bih': ['Bihari languages', 'bh', 'bih'],
 'bik': ['Bikol', ' ', 'bik'],
 'bin': ['Edo', ' ', 'bin'],
 'bis': ['Bislama', 'bi', 'bis'],
 'bla': ['Siksika', ' ', 'bla'],
 'bm': ['Bambara', 'bm', 'bam'],
 'bn': ['Bengali', 'bn', 'ben'],
 'bnt': ['Bantu languages', ' ', 'bnt'],
 'bo': ['Tibetan', 'bo', 'tib/bod'],
 'bos': ['Bosnian', 'bs', 'bos'],
 'br': ['Breton', 'br', 'bre'],
 'bra': ['Braj', ' ', 'bra'],
 'bre': ['Breton', 'br', 'bre'],
 'bs': ['Bosnian', 'bs', 'bos'],
 'btk': ['Batak languages', ' ', 'btk'],
 'bua': ['Buriat', ' ', 'bua'],
 'bug': ['Buginese', ' ', 'bug'],
 'bul': ['Bulgarian', 'bg', 'bul'],
 'bur/mya': ['Burmese', 'my', 'bur/mya'],
 'byn': ['Blin', ' ', 'byn'],
 'bzs': ['Brazilian Sign Language', '', 'bzs'],
 'ca': ['Valencian', 'ca', 'cat'],
 'cad': ['Caddo', ' ', 'cad'],
 'cai': ['Central American Indian languages', ' ', 'cai'],
 'car': ['Galibi Carib', ' ', 'car'],
 'cat': ['Valencian', 'ca', 'cat'],
 'cau': ['Caucasian languages', ' ', 'cau'],
 'ccs': ['South Caucasian languages', '', 'ccs'],
 'ce': ['Chechen', 'ce', 'che'],
 'ceb': ['Cebuano', ' ', 'ceb'],
 'cel': ['Celtic languages', ' ', 'cel'],
 'ch': ['Chamorro', 'ch', 'cha'],
 'cha': ['Chamorro', 'ch', 'cha'],
 'chb': ['Chibcha', ' ', 'chb'],
 'che': ['Chechen', 'ce', 'che'],
 'chg': ['Chagatai', ' ', 'chg'],
 'chi/zho': ['Chinese', 'zh', 'chi/zho'],
 'chk': ['Chuukese', ' ', 'chk'],
 'chm': ['Mari', ' ', 'chm'],
 'chn': ['Chinook jargon', ' ', 'chn'],
 'cho': ['Choctaw', ' ', 'cho'],
 'chp': ['Dene Suline', ' ', 'chp'],
 'chr': ['Cherokee', ' ', 'chr'],
 'chu': ['Old Slavonic', 'cu', 'chu'],
 'chv': ['Chuvash', 'cv', 'chv'],
 'chy': ['Cheyenne', ' ', 'chy'],
 'cmc': ['Chamic languages', ' ', 'cmc'],
 'cnr': ['Montenegrin', ' ', 'cnr'],
 'co': ['Corsican', 'co', 'cos'],
 'cop': ['Coptic', ' ', 'cop'],
 'cor': ['Cornish', 'kw', 'cor'],
 'cos': ['Corsican', 'co', 'cos'],
 'cpe': ['Creoles and pidgins, English based', ' ', 'cpe'],
 'cpf': ['Creoles and pidgins, French-based', ' ', 'cpf'],
 'cpp': ['Creoles and pidgins, Portuguese-based', ' ', 'cpp'],
 'cr': ['Cree', 'cr', 'cre'],
 'cre': ['Cree', 'cr', 'cre'],
 'crh': ['Crimean Turkish', ' ', 'crh'],
 'crp': ['Creoles and pidgins', ' ', 'crp'],
 'crs': ['Seselwa Creole French', '', 'crs'],
 'cs': ['Czech', 'cs', 'cze/ces'],
 'csb': ['Kashubian', ' ', 'csb'],
 'csg': ['Chilean Sign Language', '', 'csg'],
 'csn': ['Colombian Sign Language', '', 'csn'],
 'cu': ['Old Slavonic', 'cu', 'chu'],
 'cus': ['Cushitic languages', ' ', 'cus'],
 'cv': ['Chuvash', 'cv', 'chv'],
 'cy': ['Welsh', 'cy', 'wel/cym'],
 'cze': ['Czech', 'cs', 'cze'],
 'ces': ['Czech', 'cs', 'ces'],
 'da': ['Danish', 'da', 'dan'],
 'dak': ['Dakota', ' ', 'dak'],
 'dan': ['Danish', 'da', 'dan'],
 'dar': ['Dargwa', ' ', 'dar'],
 'day': ['Land Dayak languages', ' ', 'day'],
 'de': ['German', 'de', 'ger/deu'],
 'del': ['Delaware', ' ', 'del'],
 'den': ['Slave (Athapascan)', ' ', 'den'],
 'dgr': ['Dogrib', ' ', 'dgr'],
 'din': ['Dinka', ' ', 'din'],
 'div': ['Maldivian', 'dv', 'div'],
 'doi': ['Dogri', ' ', 'doi'],
 'dra': ['Dravidian languages', ' ', 'dra'],
 'dsb': ['Lower Sorbian', ' ', 'dsb'],
 'dua': ['Duala', ' ', 'dua'],
 'dum': ['Dutch, Middle (ca.1050-1350)', ' ', 'dum'],
 'dut': ['Dutch; Flemish', 'nl', 'nld'],
 'nld': ['Dutch; Flemish', 'nl', 'dut'],
 'dv': ['Maldivian', 'dv', 'div'],
 'dyu': ['Dyula', ' ', 'dyu'],
 'dz': ['Dzongkha', 'dz', 'dzo'],
 'dzo': ['Dzongkha', 'dz', 'dzo'],
 'ee': ['Ewe', 'ee', 'ewe'],
 'efi': ['Efik', ' ', 'efi'],
 'egy': ['Egyptian (Ancient)', ' ', 'egy'],
 'eka': ['Ekajuk', ' ', 'eka'],
 'el': ['Greek, Modern (1453-)', 'el', 'gre/ell'],
 'elx': ['Elamite', ' ', 'elx'],
 'en': ['English', 'en', 'eng'],
 'eng': ['English', 'en', 'eng'],
 'enm': ['English, Middle (1100-1500)', ' ', 'enm'],
 'eo': ['Esperanto', 'eo', 'epo'],
 'epo': ['Esperanto', 'eo', 'epo'],
 'es': ['Spanish', 'es', 'spa'],
 'est': ['Estonian', 'et', 'est'],
 'et': ['Estonian', 'et', 'est'],
 'eu': ['Basque', 'eu', 'baq/eus'],
 'euq': ['Basque (family)', '', 'euq'],
 'ewe': ['Ewe', 'ee', 'ewe'],
 'ewo': ['Ewondo', ' ', 'ewo'],
 'fa': ['Persian', 'fa', 'per/fas'],
 'fan': ['Fang', ' ', 'fan'],
 'fao': ['Faroese', 'fo', 'fao'],
 'fat': ['Fanti', ' ', 'fat'],
 'ff': ['Fulah', 'ff', 'ful'],
 'fi': ['Finnish', 'fi', 'fin'],
 'fij': ['Fijian', 'fj', 'fij'],
 'fil': ['Pilipino', ' ', 'fil'],
 'fin': ['Finnish', 'fi', 'fin'],
 'fiu': ['Finno-Ugrian languages', ' ', 'fiu'],
 'fj': ['Fijian', 'fj', 'fij'],
 'fo': ['Faroese', 'fo', 'fao'],
 'fon': ['Fon', ' ', 'fon'],
 'fr': ['French', 'fr', 'fre/fra'],
 'fre': ['French', 'fr', 'fre'],
 'fra': ['French', 'fr', 'fra'],
 'frm': ['French, Middle (ca.1400-1600)', ' ', 'frm'],
 'fro': ['French, Old (842-ca.1400)', ' ', 'fro'],
 'frr': ['Northern Frisian', ' ', 'frr'],
 'frs': ['Eastern Frisian', ' ', 'frs'],
 'fry': ['Western Frisian', 'fy', 'fry'],
 'fse': ['Finnish Sign Language', '', 'fse'],
 'ful': ['Fulah', 'ff', 'ful'],
 'fur': ['Friulian', ' ', 'fur'],
 'fy': ['Western Frisian', 'fy', 'fry'],
 'ga': ['Irish', 'ga', 'gle'],
 'gaa': ['Ga', ' ', 'gaa'],
 'gay': ['Gayo', ' ', 'gay'],
 'gba': ['Gbaya', ' ', 'gba'],
 'gd': ['Scottish Gaelic', 'gd', 'gla'],
 'gem': ['Germanic languages', ' ', 'gem'],
 'geo/kat': ['Georgian', 'ka', 'geo/kat'],
 'ger/deu': ['German', 'de', 'ger/deu'],
 'gez': ['Geez', ' ', 'gez'],
 'gil': ['Gilbertese', ' ', 'gil'],
 'gl': ['Galician', 'gl', 'glg'],
 'gla': ['Scottish Gaelic', 'gd', 'gla'],
 'gle': ['Irish', 'ga', 'gle'],
 'glg': ['Galician', 'gl', 'glg'],
 'glv': ['Manx', 'gv', 'glv'],
 'gmh': ['German, Middle High (ca.1050-1500)', ' ', 'gmh'],
 'gmq': ['North Germanic languages', '', 'gmq'],
 'gmw': ['West Germanic languages', '', 'gmw'],
 'gn': ['Guarani', 'gn', 'grn'],
 'goh': ['German, Old High (ca.750-1050)', ' ', 'goh'],
 'gon': ['Gondi', ' ', 'gon'],
 'gor': ['Gorontalo', ' ', 'gor'],
 'got': ['Gothic', ' ', 'got'],
 'grb': ['Grebo', ' ', 'grb'],
 'grc': ['Greek, Ancient (to 1453)', ' ', 'grc'],
 'gre/ell': ['Greek, Modern (1453-)', 'el', 'gre/ell'],
 'grk': ['Greek languages', '', 'grk'],
 'grn': ['Guarani', 'gn', 'grn'],
 'gsw': ['Swiss German', ' ', 'gsw'],
 'gu': ['Gujarati', 'gu', 'guj'],
 'guj': ['Gujarati', 'gu', 'guj'],
 'guw': ['Gun', '', 'guw'],
 'gv': ['Manx', 'gv', 'glv'],
 'gwi': ["Gwich'in", ' ', 'gwi'],
 'ha': ['Hausa', 'ha', 'hau'],
 'hai': ['Haida', ' ', 'hai'],
 'hat': ['Haitian Creole', 'ht', 'hat'],
 'hau': ['Hausa', 'ha', 'hau'],
 'haw': ['Hawaiian', ' ', 'haw'],
 'he': ['Hebrew', 'he', 'heb'],
 'heb': ['Hebrew', 'he', 'heb'],
 'her': ['Herero', 'hz', 'her'],
 'hi': ['Hindi', 'hi', 'hin'],
 'hil': ['Hiligaynon', ' ', 'hil'],
 'him': ['Western Pahari languages', ' ', 'him'],
 'hin': ['Hindi', 'hi', 'hin'],
 'hit': ['Hittite', ' ', 'hit'],
 'hmn': ['Mong', ' ', 'hmn'],
 'hmo': ['Hiri Motu', 'ho', 'hmo'],
 'ho': ['Hiri Motu', 'ho', 'hmo'],
 'hr': ['Croatian', 'hr', 'hrv'],
 'hrv': ['Croatian', 'hr', 'hrv'],
 'hsb': ['Upper Sorbian', ' ', 'hsb'],
 'ht': ['Haitian Creole', 'ht', 'hat'],
 'hu': ['Hungarian', 'hu', 'hun'],
 'hun': ['Hungarian', 'hu', 'hun'],
 'hup': ['Hupa', ' ', 'hup'],
 'hy': ['Armenian', 'hy', 'arm/hye'],
 'hz': ['Herero', 'hz', 'her'],
 'ia': ['Interlingua (International Auxiliary Language Association)',
  'ia',
  'ina'],
 'iba': ['Iban', ' ', 'iba'],
 'ibo': ['Igbo', 'ig', 'ibo'],
 'ice/isl': ['Icelandic', 'is', 'ice/isl'],
 'id': ['Indonesian', 'id', 'ind'],
 'ido': ['Ido', 'io', 'ido'],
 'ie': ['Occidental', 'ie', 'ile'],
 'ig': ['Igbo', 'ig', 'ibo'],
 'ii': ['Sichuan Yi', 'ii', 'iii'],
 'iii': ['Sichuan Yi', 'ii', 'iii'],
 'iir': ['Indo-Iranian languages', '', 'iir'],
 'ijo': ['Ijo languages', ' ', 'ijo'],
 'ik': ['Inupiaq', 'ik', 'ipk'],
 'iku': ['Inuktitut', 'iu', 'iku'],
 'ile': ['Occidental', 'ie', 'ile'],
 'ilo': ['Iloko', ' ', 'ilo'],
 'ina': ['Interlingua (International Auxiliary Language Association)',
  'ia',
  'ina'],
 'inc': ['Indic languages', ' ', 'inc'],
 'ind': ['Indonesian', 'id', 'ind'],
 'ine': ['Indo-European languages', ' ', 'ine'],
 'inh': ['Ingush', ' ', 'inh'],
 'io': ['Ido', 'io', 'ido'],
 'ipk': ['Inupiaq', 'ik', 'ipk'],
 'ira': ['Iranian languages', ' ', 'ira'],
 'iro': ['Iroquoian languages', ' ', 'iro'],
 'is': ['Icelandic', 'is', 'ice/isl'],
 'iso': ['Isoko', '', 'iso'],
 'it': ['Italian', 'it', 'ita'],
 'ita': ['Italian', 'it', 'ita'],
 'itc': ['Italic languages', '', 'itc'],
 'iu': ['Inuktitut', 'iu', 'iku'],
 'ja': ['Japanese', 'ja', 'jpn'],
 'jap': ['Japanese', '', 'jap'],
 'jav': ['Javanese', 'jv', 'jav'],
 'jbo': ['Lojban', ' ', 'jbo'],
 'jpn': ['Japanese', 'ja', 'jpn'],
 'jpr': ['Judeo-Persian', ' ', 'jpr'],
 'jrb': ['Judeo-Arabic', ' ', 'jrb'],
 'jv': ['Javanese', 'jv', 'jav'],
 'ka': ['Georgian', 'ka', 'geo/kat'],
 'kaa': ['Kara-Kalpak', ' ', 'kaa'],
 'kab': ['Kabyle', ' ', 'kab'],
 'kac': ['Kachin', ' ', 'kac'],
 'kal': ['Kalaallisut', 'kl', 'kal'],
 'kam': ['Kamba', ' ', 'kam'],
 'kan': ['Kannada', 'kn', 'kan'],
 'kar': ['Karen languages', ' ', 'kar'],
 'kas': ['Kashmiri', 'ks', 'kas'],
 'kau': ['Kanuri', 'kr', 'kau'],
 'kaw': ['Kawi', ' ', 'kaw'],
 'kaz': ['Kazakh', 'kk', 'kaz'],
 'kbd': ['Kabardian', ' ', 'kbd'],
 'kg': ['Kongo', 'kg', 'kon'],
 'kha': ['Khasi', ' ', 'kha'],
 'khi': ['Khoisan languages', ' ', 'khi'],
 'khm': ['Central Khmer', 'km', 'khm'],
 'kho': ['Sakan', ' ', 'kho'],
 'ki': ['Kikuyu', 'ki', 'kik'],
 'kik': ['Kikuyu', 'ki', 'kik'],
 'kin': ['Kinyarwanda', 'rw', 'kin'],
 'kir': ['Kyrgyz', 'ky', 'kir'],
 'kj': ['Kwanyama', 'kj', 'kua'],
 'kk': ['Kazakh', 'kk', 'kaz'],
 'kl': ['Kalaallisut', 'kl', 'kal'],
 'km': ['Central Khmer', 'km', 'khm'],
 'kmb': ['Kimbundu', ' ', 'kmb'],
 'kn': ['Kannada', 'kn', 'kan'],
 'ko': ['Korean', 'ko', 'kor'],
 'kok': ['Konkani', ' ', 'kok'],
 'kom': ['Komi', 'kv', 'kom'],
 'kon': ['Kongo', 'kg', 'kon'],
 'kor': ['Korean', 'ko', 'kor'],
 'kos': ['Kosraean', ' ', 'kos'],
 'kpe': ['Kpelle', ' ', 'kpe'],
 'kqn': ['Kaonde', '', 'kqn'],
 'kr': ['Kanuri', 'kr', 'kau'],
 'krc': ['Karachay-Balkar', ' ', 'krc'],
 'krl': ['Karelian', ' ', 'krl'],
 'kro': ['Kru languages', ' ', 'kro'],
 'kru': ['Kurukh', ' ', 'kru'],
 'ks': ['Kashmiri', 'ks', 'kas'],
 'ku': ['Kurdish', 'ku', 'kur'],
 'kua': ['Kwanyama', 'kj', 'kua'],
 'kum': ['Kumyk', ' ', 'kum'],
 'kur': ['Kurdish', 'ku', 'kur'],
 'kut': ['Kutenai', ' ', 'kut'],
 'kv': ['Komi', 'kv', 'kom'],
 'kw': ['Cornish', 'kw', 'cor'],
 'kwn': ['Kwangali', '', 'kwn'],
 'kwy': ['San Salvador Kongo', '', 'kwy'],
 'ky': ['Kyrgyz', 'ky', 'kir'],
 'la': ['Latin', 'la', 'lat'],
 'lad': ['Ladino', ' ', 'lad'],
 'lah': ['Lahnda', ' ', 'lah'],
 'lam': ['Lamba', ' ', 'lam'],
 'lao': ['Lao', 'lo', 'lao'],
 'lat': ['Latin', 'la', 'lat'],
 'lav': ['Latvian', 'lv', 'lav'],
 'lb': ['Luxembourgish', 'lb', 'ltz'],
 'lez': ['Lezghian', ' ', 'lez'],
 'lg': ['Ganda', 'lg', 'lug'],
 'li': ['Limburgish', 'li', 'lim'],
 'lim': ['Limburgish', 'li', 'lim'],
 'lin': ['Lingala', 'ln', 'lin'],
 'lit': ['Lithuanian', 'lt', 'lit'],
 'ln': ['Lingala', 'ln', 'lin'],
 'lo': ['Lao', 'lo', 'lao'],
 'lol': ['Mongo', ' ', 'lol'],
 'loz': ['Lozi', ' ', 'loz'],
 'lt': ['Lithuanian', 'lt', 'lit'],
 'ltz': ['Luxembourgish', 'lb', 'ltz'],
 'lu': ['Luba-Katanga', 'lu', 'lub'],
 'lua': ['Luba-Lulua', ' ', 'lua'],
 'lub': ['Luba-Katanga', 'lu', 'lub'],
 'lue': ['Luvale', '', 'lue'],
 'lug': ['Ganda', 'lg', 'lug'],
 'lui': ['Luiseno', ' ', 'lui'],
 'lun': ['Lunda', ' ', 'lun'],
 'luo': ['Luo (Kenya and Tanzania)', ' ', 'luo'],
 'lus': ['Lushai', ' ', 'lus'],
 'lv': ['Latvian', 'lv', 'lav'],
 'mac/mkd': ['Macedonian', 'mk', 'mac/mkd'],
 'mad': ['Madurese', ' ', 'mad'],
 'mag': ['Magahi', ' ', 'mag'],
 'mah': ['Marshallese', 'mh', 'mah'],
 'mai': ['Maithili', ' ', 'mai'],
 'mak': ['Makasar', ' ', 'mak'],
 'mal': ['Malayalam', 'ml', 'mal'],
 'man': ['Mandingo', ' ', 'man'],
 'mao/mri': ['Maori', 'mi', 'mao/mri'],
 'map': ['Austronesian languages', ' ', 'map'],
 'mar': ['Marathi', 'mr', 'mar'],
 'mas': ['Masai', ' ', 'mas'],
 'may/msa': ['Malay', 'ms', 'may/msa'],
 'mdf': ['Moksha', ' ', 'mdf'],
 'mdr': ['Mandar', ' ', 'mdr'],
 'men': ['Mende', ' ', 'men'],
 'mfe': ['Morisyen', '', 'mfe'],
 'mfs': ['Mexican Sign Language', '', 'mfs'],
 'mg': ['Malagasy', 'mg', 'mlg'],
 'mga': ['Irish, Middle (900-1200)', ' ', 'mga'],
 'mh': ['Marshallese', 'mh', 'mah'],
 'mi': ['Maori', 'mi', 'mao/mri'],
 'mic': ['Micmac', ' ', 'mic'],
 'min': ['Minangkabau', ' ', 'min'],
 'mis': ['Uncoded languages', ' ', 'mis'],
 'mk': ['Macedonian', 'mk', 'mac/mkd'],
 'mkh': ['Mon-Khmer languages', ' ', 'mkh'],
 'ml': ['Malayalam', 'ml', 'mal'],
 'mlg': ['Malagasy', 'mg', 'mlg'],
 'mlt': ['Maltese', 'mt', 'mlt'],
 'mn': ['Mongolian', 'mn', 'mon'],
 'mnc': ['Manchu', ' ', 'mnc'],
 'mni': ['Manipuri', ' ', 'mni'],
 'mno': ['Manobo languages', ' ', 'mno'],
 'moh': ['Mohawk', ' ', 'moh'],
 'mon': ['Mongolian', 'mn', 'mon'],
 'mos': ['Mossi', ' ', 'mos'],
 'mr': ['Marathi', 'mr', 'mar'],
 'ms': ['Malay', 'ms', 'may/msa'],
 'mt': ['Maltese', 'mt', 'mlt'],
 'mul': ['Multiple languages', ' ', 'mul'],
 'mun': ['Munda languages', ' ', 'mun'],
 'mus': ['Creek', ' ', 'mus'],
 'mwl': ['Mirandese', ' ', 'mwl'],
 'mwr': ['Marwari', ' ', 'mwr'],
 'my': ['Burmese', 'my', 'bur/mya'],
 'myn': ['Mayan languages', ' ', 'myn'],
 'myv': ['Erzya', ' ', 'myv'],
 'na': ['Nauru', 'na', 'nau'],
 'nah': ['Nahuatl languages', ' ', 'nah'],
 'nai': ['North American Indian languages', ' ', 'nai'],
 'nap': ['Neapolitan', ' ', 'nap'],
 'nau': ['Nauru', 'na', 'nau'],
 'nav': ['Navajo', 'nv', 'nav'],
 'nb': ['Norwegian Bokmål', 'nb', 'nob'],
 'nbl': ['South Ndebele', 'nr', 'nbl'],
 'nd': ['North Ndebele', 'nd', 'nde'],
 'nde': ['North Ndebele', 'nd', 'nde'],
 'ndo': ['Ndonga', 'ng', 'ndo'],
 'nds': ['Saxon, Low', ' ', 'nds'],
 'ne': ['Nepali', 'ne', 'nep'],
 'nep': ['Nepali', 'ne', 'nep'],
 'new': ['Newari', ' ', 'new'],
 'ng': ['Ndonga', 'ng', 'ndo'],
 'nia': ['Nias', ' ', 'nia'],
 'nic': ['Niger-Kordofanian languages', ' ', 'nic'],
 'niu': ['Niuean', ' ', 'niu'],
 'nl': ['Flemish', 'nl', 'dut/nld'],
 'nn': ['Nynorsk, Norwegian', 'nn', 'nno'],
 'nno': ['Nynorsk, Norwegian', 'nn', 'nno'],
 'no': ['Norwegian', 'no', 'nor'],
 'nob': ['Norwegian Bokmål', 'nb', 'nob'],
 'nog': ['Nogai', ' ', 'nog'],
 'non': ['Norse, Old', ' ', 'non'],
 'nor': ['Norwegian', 'no', 'nor'],
 'nqo': ["N'Ko", ' ', 'nqo'],
 'nr': ['South Ndebele', 'nr', 'nbl'],
 'nso': ['Sotho, Northern', ' ', 'nso'],
 'nub': ['Nubian languages', ' ', 'nub'],
 'nv': ['Navajo', 'nv', 'nav'],
 'nwc': ['Old Newari', ' ', 'nwc'],
 'ny': ['Nyanja', 'ny', 'nya'],
 'nya': ['Nyanja', 'ny', 'nya'],
 'nyk': ['Nyaneka', '', 'nyk'],
 'nym': ['Nyamwezi', ' ', 'nym'],
 'nyn': ['Nyankole', ' ', 'nyn'],
 'nyo': ['Nyoro', ' ', 'nyo'],
 'nzi': ['Nzima', ' ', 'nzi'],
 'oc': ['Occitan (post 1500)', 'oc', 'oci'],
 'oci': ['Occitan (post 1500)', 'oc', 'oci'],
 'oj': ['Ojibwa', 'oj', 'oji'],
 'oji': ['Ojibwa', 'oj', 'oji'],
 'om': ['Oromo', 'om', 'orm'],
 'or': ['Oriya', 'or', 'ori'],
 'ori': ['Oriya', 'or', 'ori'],
 'orm': ['Oromo', 'om', 'orm'],
 'os': ['Ossetic', 'os', 'oss'],
 'osa': ['Osage', ' ', 'osa'],
 'oss': ['Ossetic', 'os', 'oss'],
 'ota': ['Turkish, Ottoman (1500-1928)', ' ', 'ota'],
 'oto': ['Otomian languages', ' ', 'oto'],
 'pa': ['Punjabi', 'pa', 'pan'],
 'paa': ['Papuan languages', ' ', 'paa'],
 'pag': ['Pangasinan', ' ', 'pag'],
 'pal': ['Pahlavi', ' ', 'pal'],
 'pam': ['Pampanga', ' ', 'pam'],
 'pan': ['Punjabi', 'pa', 'pan'],
 'pap': ['Papiamento', ' ', 'pap'],
 'pau': ['Palauan', ' ', 'pau'],
 'peo': ['Persian, Old (ca.600-400 B.C.)', ' ', 'peo'],
 'per': ['Persian', 'fa', 'fas'],
 'fas': ['Persian', 'fa', 'per'],
 'phi': ['Philippine languages', ' ', 'phi'],
 'phn': ['Phoenician', ' ', 'phn'],
 'pi': ['Pali', 'pi', 'pli'],
 'pis': ['Pijin', '', 'pis'],
 'pl': ['Polish', 'pl', 'pol'],
 'pli': ['Pali', 'pi', 'pli'],
 'pol': ['Polish', 'pl', 'pol'],
 'pon': ['Pohnpeian', ' ', 'pon'],
 'por': ['Portuguese', 'pt', 'por'],
 'poz': ['Malayo-Polynesian languages', '', 'poz'],
 'pqe': ['Eastern Malayo-Polynesian languages', '', 'pqe'],
 'pqw': ['Western Malayo-Polynesian languages', '', 'pqw'],
 'pra': ['Prakrit languages', ' ', 'pra'],
 'prl': ['Peruvian Sign Language', '', 'prl'],
 'pro': ['Provençal, Old (to 1500)', ' ', 'pro'],
 'ps': ['Pushto', 'ps', 'pus'],
 'pt': ['Portuguese', 'pt', 'por'],
 'pus': ['Pushto', 'ps', 'pus'],
 'qaa-qtz': ['Reserved for local use', ' ', 'qaa-qtz'],
 'qu': ['Quechua', 'qu', 'que'],
 'que': ['Quechua', 'qu', 'que'],
 'raj': ['Rajasthani', ' ', 'raj'],
 'rap': ['Rapanui', ' ', 'rap'],
 'rar': ['Rarotongan', ' ', 'rar'],
 'rm': ['Romansh', 'rm', 'roh'],
 'rn': ['Rundi', 'rn', 'run'],
 'rnd': ['Ruund', '', 'rnd'],
 'ro': ['Romanian', 'ro', 'rum/ron'],
 'roa': ['Romance languages', ' ', 'roa'],
 'roh': ['Romansh', 'rm', 'roh'],
 'rom': ['Romany', ' ', 'rom'],
 'ru': ['Russian', 'ru', 'rus'],
 'rum/ron': ['Romanian', 'ro', 'rum/ron'],
 'run': ['Rundi', 'rn', 'run'],
 'rup': ['Macedo-Romanian', ' ', 'rup'],
 'rus': ['Russian', 'ru', 'rus'],
 'rw': ['Kinyarwanda', 'rw', 'kin'],
 'sa': ['Sanskrit', 'sa', 'san'],
 'sad': ['Sandawe', ' ', 'sad'],
 'sag': ['Sango', 'sg', 'sag'],
 'sah': ['Yakut', ' ', 'sah'],
 'sai': ['South American Indian languages', ' ', 'sai'],
 'sal': ['Salishan languages', ' ', 'sal'],
 'sam': ['Samaritan Aramaic', ' ', 'sam'],
 'san': ['Sanskrit', 'sa', 'san'],
 'sas': ['Sasak', ' ', 'sas'],
 'sat': ['Santali', ' ', 'sat'],
 'sc': ['Sardinian', 'sc', 'srd'],
 'scn': ['Sicilian', ' ', 'scn'],
 'sco': ['Scots', ' ', 'sco'],
 'sd': ['Sindhi', 'sd', 'snd'],
 'se': ['Northern Sami', 'se', 'sme'],
 'sel': ['Selkup', ' ', 'sel'],
 'sem': ['Semitic languages', ' ', 'sem'],
 'sg': ['Sango', 'sg', 'sag'],
 'sga': ['Irish, Old (to 900)', ' ', 'sga'],
 'sgn': ['Sign Languages', ' ', 'sgn'],
 'sh': ['Serbo-Croatian', 'sh', ''],
 'shn': ['Shan', ' ', 'shn'],
 'si': ['Sinhalese', 'si', 'sin'],
 'sid': ['Sidamo', ' ', 'sid'],
 'sin': ['Sinhalese', 'si', 'sin'],
 'sio': ['Siouan languages', ' ', 'sio'],
 'sit': ['Sino-Tibetan languages', ' ', 'sit'],
 'sk': ['Slovak', 'sk', 'slo/slk'],
 'sl': ['Slovenian', 'sl', 'slv'],
 'sla': ['Slavic languages', ' ', 'sla'],
 'slo/slk': ['Slovak', 'sk', 'slo/slk'],
 'slv': ['Slovenian', 'sl', 'slv'],
 'sm': ['Samoan', 'sm', 'smo'],
 'sma': ['Southern Sami', ' ', 'sma'],
 'sme': ['Northern Sami', 'se', 'sme'],
 'smi': ['Sami languages', ' ', 'smi'],
 'smj': ['Lule Sami', ' ', 'smj'],
 'smn': ['Inari Sami', ' ', 'smn'],
 'smo': ['Samoan', 'sm', 'smo'],
 'sms': ['Skolt Sami', ' ', 'sms'],
 'sn': ['Shona', 'sn', 'sna'],
 'sna': ['Shona', 'sn', 'sna'],
 'snd': ['Sindhi', 'sd', 'snd'],
 'snk': ['Soninke', ' ', 'snk'],
 'so': ['Somali', 'so', 'som'],
 'sog': ['Sogdian', ' ', 'sog'],
 'som': ['Somali', 'so', 'som'],
 'son': ['Songhai languages', ' ', 'son'],
 'sot': ['Sotho, Southern', 'st', 'sot'],
 'spa': ['Spanish', 'es', 'spa'],
 'sq': ['Albanian', 'sq', 'alb/sqi'],
 'sr': ['Serbian', 'sr', 'srp'],
 'srd': ['Sardinian', 'sc', 'srd'],
 'srn': ['Sranan Tongo', ' ', 'srn'],
 'srp': ['Serbian', 'sr', 'srp'],
 'srr': ['Serer', ' ', 'srr'],
 'ss': ['Swati', 'ss', 'ssw'],
 'ssa': ['Nilo-Saharan languages', ' ', 'ssa'],
 'ssp': ['Spanish Sign Language', '', 'ssp'],
 'ssw': ['Swati', 'ss', 'ssw'],
 'st': ['Sotho, Southern', 'st', 'sot'],
 'su': ['Sundanese', 'su', 'sun'],
 'suk': ['Sukuma', ' ', 'suk'],
 'sun': ['Sundanese', 'su', 'sun'],
 'sus': ['Susu', ' ', 'sus'],
 'sux': ['Sumerian', ' ', 'sux'],
 'sv': ['Swedish', 'sv', 'swe'],
 'sw': ['Swahili', 'sw', 'swa'],
 'swa': ['Swahili', 'sw', 'swa'],
 'swc': ['Congo Swahili', '', 'swc'],
 'swe': ['Swedish', 'sv', 'swe'],
 'syc': ['Classical Syriac', ' ', 'syc'],
 'syr': ['Syriac', ' ', 'syr'],
 'ta': ['Tamil', 'ta', 'tam'],
 'tah': ['Tahitian', 'ty', 'tah'],
 'tai': ['Tai languages', ' ', 'tai'],
 'tam': ['Tamil', 'ta', 'tam'],
 'tat': ['Tatar', 'tt', 'tat'],
 'taw': ['Tai', '', 'taw'],
 'tdt': ['Tetun Dili', '', 'tdt'],
 'te': ['Telugu', 'te', 'tel'],
 'tel': ['Telugu', 'te', 'tel'],
 'tem': ['Timne', ' ', 'tem'],
 'ter': ['Tereno', ' ', 'ter'],
 'tet': ['Tetum', ' ', 'tet'],
 'tg': ['Tajik', 'tg', 'tgk'],
 'tgk': ['Tajik', 'tg', 'tgk'],
 'tgl': ['Tagalog', 'tl', 'tgl'],
 'th': ['Thai', 'th', 'tha'],
 'tha': ['Thai', 'th', 'tha'],
 'ti': ['Tigrinya', 'ti', 'tir'],
 'tib/bod': ['Tibetan', 'bo', 'tib/bod'],
 'tig': ['Tigre', ' ', 'tig'],
 'tir': ['Tigrinya', 'ti', 'tir'],
 'tiv': ['Tiv', ' ', 'tiv'],
 'tk': ['Turkmen', 'tk', 'tuk'],
 'tkl': ['Tokelau', ' ', 'tkl'],
 'tl': ['Tagalog', 'tl', 'tgl'],
 'tlh': ['tlhIngan-Hol', ' ', 'tlh'],
 'tli': ['Tlingit', ' ', 'tli'],
 'tll': ['Tetela', '', 'tll'],
 'tmh': ['Tamashek', ' ', 'tmh'],
 'tn': ['Tswana', 'tn', 'tsn'],
 'to': ['Tonga (Tonga Islands)', 'to', 'ton'],
 'tog': ['Tonga (Nyasa)', ' ', 'tog'],
 'toi': ['Tonga (Zambia)', '', 'toi'],
 'ton': ['Tonga (Tonga Islands)', 'to', 'ton'],
 'tpi': ['Tok Pisin', ' ', 'tpi'],
 'tr': ['Turkish', 'tr', 'tur'],
 'trk': ['Turkic languages', '', 'trk'],
 'ts': ['Tsonga', 'ts', 'tso'],
 'tsi': ['Tsimshian', ' ', 'tsi'],
 'tsn': ['Tswana', 'tn', 'tsn'],
 'tso': ['Tsonga', 'ts', 'tso'],
 'tt': ['Tatar', 'tt', 'tat'],
 'tuk': ['Turkmen', 'tk', 'tuk'],
 'tum': ['Tumbuka', ' ', 'tum'],
 'tup': ['Tupi languages', ' ', 'tup'],
 'tur': ['Turkish', 'tr', 'tur'],
 'tut': ['Altaic languages', ' ', 'tut'],
 'tvl': ['Tuvalu', ' ', 'tvl'],
 'tw': ['Twi', 'tw', 'twi'],
 'twi': ['Twi', 'tw', 'twi'],
 'ty': ['Tahitian', 'ty', 'tah'],
 'tyv': ['Tuvinian', ' ', 'tyv'],
 'tzo': ['Tzotzil', '', 'tzo'],
 'udm': ['Udmurt', ' ', 'udm'],
 'ug': ['Uyghur', 'ug', 'uig'],
 'uga': ['Ugaritic', ' ', 'uga'],
 'uig': ['Uyghur', 'ug', 'uig'],
 'uk': ['Ukrainian', 'uk', 'ukr'],
 'ukr': ['Ukrainian', 'uk', 'ukr'],
 'umb': ['Umbundu', ' ', 'umb'],
 'und': ['Undetermined', ' ', 'und'],
 'ur': ['Urdu', 'ur', 'urd'],
 'urd': ['Urdu', 'ur', 'urd'],
 'urj': ['Uralic languages', '', 'urj'],
 'uz': ['Uzbek', 'uz', 'uzb'],
 'uzb': ['Uzbek', 'uz', 'uzb'],
 'vai': ['Vai', ' ', 'vai'],
 've': ['Venda', 've', 'ven'],
 'ven': ['Venda', 've', 'ven'],
 'vi': ['Vietnamese', 'vi', 'vie'],
 'vie': ['Vietnamese', 'vi', 'vie'],
 'vo': ['Volapük', 'vo', 'vol'],
 'vol': ['Volapük', 'vo', 'vol'],
 'vot': ['Votic', ' ', 'vot'],
 'vsl': ['Venezuelan Sign Language', '', 'vsl'],
 'wa': ['Walloon', 'wa', 'wln'],
 'wak': ['Wakashan languages', ' ', 'wak'],
 'wal': ['Wolaytta', ' ', 'wal'],
 'war': ['Waray', ' ', 'war'],
 'was': ['Washo', ' ', 'was'],
 'wel/cym': ['Welsh', 'cy', 'wel/cym'],
 'wen': ['Sorbian languages', ' ', 'wen'],
 'wln': ['Walloon', 'wa', 'wln'],
 'wls': ['Wallisian', '', 'wls'],
 'wo': ['Wolof', 'wo', 'wol'],
 'wol': ['Wolof', 'wo', 'wol'],
 'xal': ['Oirat', ' ', 'xal'],
 'xh': ['Xhosa', 'xh', 'xho'],
 'xho': ['Xhosa', 'xh', 'xho'],
 'yao': ['Yao', ' ', 'yao'],
 'yap': ['Yapese', ' ', 'yap'],
 'yi': ['Yiddish', 'yi', 'yid'],
 'yid': ['Yiddish', 'yi', 'yid'],
 'yo': ['Yoruba', 'yo', 'yor'],
 'yor': ['Yoruba', 'yo', 'yor'],
 'ypk': ['Yupik languages', ' ', 'ypk'],
 'yua': ['Yucateco', '', 'yua'],
 'za': ['Zhuang', 'za', 'zha'],
 'zai': ['Isthmus Zapotec', '', 'zai'],
 'zap': ['Zapotec', ' ', 'zap'],
 'zbl': ['Blissymbols', ' ', 'zbl'],
 'zen': ['Zenaga', ' ', 'zen'],
 'zgh': ['Standard Moroccan Tamazight', ' ', 'zgh'],
 'zh': ['Chinese', 'zh', 'chi/zho'],
 'zha': ['Zhuang', 'za', 'zha'],
 'zle': ['East Slavic languages ', '', 'zle'],
 'zls': ['South Slavic languages', '', 'zls'],
 'zlw': ['West Slavic languages', '', 'zlw'],
 'znd': ['Zande languages', ' ', 'znd'],
 'zne': ['Zande (individual language)', '', 'zne'],
 'zu': ['Zulu', 'zu', 'zul'],
 'zul': ['Zulu', 'zu', 'zul'],
 'zun': ['Zuni', ' ', 'zun'],
 'zxx': ['Not applicable', ' ', 'zxx'],
 'zza': ['Zazaki', ' ', 'zza']
 }

rtl_languages = ['ar', 'ur', 'he', 
                 'fa']